### ISSUE TITLE
Throws an error

### ISSUE THREAD

**Issue by jcrben** [mumba/dmport#1]
I get this error when trying to use it:
```
~$ dmport
An option is required
~$ dmport -x dev2
exec error { [Error: Command failed: /bin/sh -c docker-machine env dev2
Error checking TLS connection: Host is not running
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c docker-machine env dev2' }
~$ dmport -x dev2
buffer.js:139
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at /Users/MacbookRetina/dotfiles/local/nodenv/versions/4.2.2/lib/node_modules/@mumbacloud/dmport/index.js:168:56
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:368:12)
~$ dmport --version
0.0.16
~$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
dev    -        virtualbox   Error                                         Unknown   machine does not exist
dev2   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.3
```

**Comment by gregkeys** [comment]
what happens when you type `docker-machine env dev2`

**Comment by jcrben** [comment]
`Host does not exist: "dev2"` ... hmm

this is because I deleted the machine after I'd created it - lemme see if I can reproduce. Here's a better version:

```
~$ dm env dev-test
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/MacbookRetina/.config/docker/machine/machines/dev-test"
export DOCKER_MACHINE_NAME="dev-test"
# Run this command to configure your shell:
# eval $(docker-machine env dev-test)
~$ dmport --export dev-test
buffer.js:139
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at /Users/MacbookRetina/dotfiles/local/nodenv/versions/4.2.2/lib/node_modules/@mumbacloud/dmport/index.js:168:56
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:368:12)
```

**Comment by gregkeys** [comment]
are you using docker for mac or docker toolbox or something else?

**Comment by gregkeys** [comment]
k I see the problem /Users/MacbookRetina/`.config`/docker/machine/machines/dev-test docker used to put them in a .docker directory so that got hard coded into dmport.... I need to refactor this pay off some technical debt and make that location more dynamic.

Im going to add a hack for now just so you can use the module, but I plan to refactor the whole thing later this week.

**Comment by gregkeys** [comment]
Hmm correction, that is going to be a problem on the import... still not 100% the cause on the export

**Comment by jcrben** [comment]
Hey, thanks! The tool isn't a huge need for me, but I appreciate the work.
